alxshelepenok/gatsby-starter-lumen

components/ReadNext/index.jsx

The component didn't render because pages were undefined.
I found that they are stored inside the route object.
This fixed it for me.

Fixes not rendering of ReadNext component

---

components/SitePage/index.jsx
components/SitePost/index.jsx
pages/index.jsx

Here are fixes that should close #25.
Added a key to pageLinks within SiteIndex to remove warning that key is required when creating a list of elements.
Update required prop for SitePost by changing required prop from `post` to `route` and removing propType for `pages`.  These are objects on `route` prop and not passed in individually.
Let me know if you have questions or would like changes.
Axel

Updates to remove React warnings

---

components/SiteSidebar/index.jsx

Addresses [issue: 32](https://github.com/wpioneer/gatsby-starter-lumen/issues/32)
I created the PR from within Github. It added a newline to the file.

prefixLink unnecessary for profilePic Closes #32

---

src/components/Links/index.jsx

Noticed adding my author info inside the gatsby-config.js did not properly update in the Links component. 
The username would be appended to the root URL.
Updated the hrefs so all you have to do is add your account names to get the proper links.

Fix hrefs for github, twitter and vk links in Links component.

---

gatsby-node.js
src/components/PostTemplateDetails/index.jsx

This commit avoids undefined.map() or null.map() is calling.
When there is no tag in a post, there are two cases in frontmatter.
1)
title: title
categories: Technical
...
2)
title: title
tags:
categories: Technical
...
Let's look at `post.node.frontmatter.tags` in both situations.
`FILE1 = /gatsby-node.js`
`FILE2 = /src/components/PostTemplateDetails/index.jsx`
In the first case, it is `undefined` in `FILE1`.
Cheking `undefined` is already implemented at FILE1#126, so undefined.map()
is not called.
But it is `null` in `FILE2#22`
and a crash will be occurred because it tries to run `null.map()`.
In the second case, it is `null` in `FILE1` and `FILE2`.
In this case, there will be two crashes in both files because both codes
try to run `null.map()`.
This commit avoids these crashes.

Fixes a crash when a post has no tag

---

src/components/Disqus/Disqus.jsx
src/components/PostTemplateDetails/index.jsx
src/templates/post-template.jsx

It is important decoupling between the node side code and the browser side code, because it allows to use the rich features of the node side. For example, I wanted to use '[dotenv](https://github.com/bkeepers/dotenv)' to keep my secret keys, but it have to be not exposed to browser side. If it is exposed, the web console complains that there is no module 'fs'. To accomplish this, the 'gatsby-config.js' file (and maybe gatsby-node.js..?) must be kept in node code.
However, it exposed into browser code because the Disqus module imports it directly.
To decouple this, all of the siteMetadata information is served via GraphQL.
This commit has this change.
I am sorry to say that, I couldn't test this PR is working on your repository code because my development environment fails to build this …

Decouple the node side code and the browser side code

---

gatsby-config.js

Set the channel link and description to match siteMetadata's URL and subtitle.
```xml
<title>Blog by John Doe</title>
<description>Blog by John Doe</description>
<link>http://github.com/dylang/node-rss</link>
```
becomes
```xml
<title>Blog by John Doe</title>
<description>Pellentesque odio nisi, euismod in, pharetra a, ultricies in, diam. Sed arcu.</description>
<link>https://lumen.netlify.com/</link>
```
also removed trailing slash in URL as it resulted in a double slash in the feed, leading to a 404
```xml
<link>https://lumen.netlify.com//posts/humane-typography-in-the-digital-age/</link>
```

Improve RSS channel defaults

---

package.json

Deploy command throws and error because --prefix-links changed to --prefix-paths as of  https://github.com/gatsbyjs/gatsby/issues/1421

Fix prefix-links error upon deploy

---

README.md
netlify.toml

Added simple Netlify deploy support. Based on https://github.com/AustinGreen/gatsby-starter-netlify-cms. Works and makes it easy for someone new to Gatsby / this starter kit to deploy and view the site (and makes changes too).
Please let me know if there are any issues! :)

Add Simple Netlify Deploy Support

---

.gitignore

Saw that this was removed in ce4665435e12320bb9ec3235f1e23440d27db14f.
It should be a part of git according to the yarn blog here:
https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

We want `yarn.lock` in git

---

README.md

I didn't know about Netlify before coming here, having a link is easier than Googling :)

Add more service urls and tweak a layout

---

src/components/Post/Content/Content.module.scss

The `.gatsby-highlight` selectors don't do anything because it doesn't have a `:global()` qualifier. The CSS styles aren't applied because the class gets changed from `gatsby-highlight` to something else due to CSS Modules:
If you wrap them in `:global()` qualifiers it works, but the styles seem to not be helpful - they make the prism.js code block off center. Since the selectors weren't doing anything to begin with, I've just removed them in this PR since they're dead code.

Removed .gatsby-highlight selectors

---

src/components/Layout/Layout.js

From Google's Lighthouse:
This PR adds the `lang` attribute to `<html>`.

Add lang="en" to <html>

---

src/templates/index-template.js

A quick codebase search for `<Sidebar` reveals that the `isIndex` prop is never used in Sidebar! I also tried setting it just to see what it looks like, and it basically changes nothing - the difference between an `h1` and `h2` in `<Author />` makes basically no visual difference. This PR removes the `isIndex` prop because it's unused and shouldn't be used.

Add isIndex prop to Sidebar in index-template

---

src/components/Post/Comments/Comments.js
src/templates/post-template.js

The `url` prop being passed into `ReactDisqusComments` is wrong - both `siteUrl` and `postSlug` are undefined:
- `siteUrl` should actually be named `url`, see the graphql in `post-template`
- `postSlug` is not included in the graphql for `post-template` and is thus `undefined`
This prop fixes those two values so now the URL is correct. I tested this on my own site (which is based on this starter project) and it works great!

Fixed url prop bug for <ReactDisqusComments />

---

gatsby-config.js
package-lock.json
package.json

Right now the template uses `gatsby-plugin-google-analytics`, which uses the outdated analytics.js. This PR migrates to use gtag.js (see Google's [migration guide](https://developers.google.com/analytics/devguides/collection/gtagjs/migration) explaining the difference) via [`gatsby-plugin-gtagjs`](https://github.com/vzhou842/gatsby-plugin-gtag.js), which is a fork of [`gatsby-plugin-gtag`](https://github.com/flpvsk/gatsby-plugin-gtag) that makes a few improvements.
Here's what the script from `gatsby-plugin-gtagjs` looks like:

Replace gatsby-plugin-google-analytics with gatsby-plugin-google-gtag

---

README.md

There is no `serve` script in the package.json. This is meant to be `gatsby serve`
Fixes the steps on testing the CMS locally.
None

Fix: Testing Netlify locally using gatsby serve

---

README.md
config.js
gatsby-config.js

We want to add the ability to customize `pathPrefix` for github pages deploys
https://github.com/alxshelepenok/gatsby-starter-lumen/issues/281
Despite what I said in https://github.com/alxshelepenok/gatsby-starter-lumen/issues/281, apparently it's super easy to add `pathPrefix` capabilities without having to modify the js code at all

add pathPrefix configuration

---

gatsby-config.js
package-lock.json
package.json

Protects us against attacks described [here](https://mathiasbynens.github.io/rel-noopener/).
The defaults set by the [plugin](https://github.com/JLongley/gatsby-remark-external-links) are `target=_blank` and `rel=nofollow noopener noreferrer`. If you want different defaults just let me know.

Add external link defaults for markdown

---

src/components/Sidebar/Contacts/Contacts.js

Hi, thank you for this awesome starter!
I made this small change for my own blog and figured it could be useful for others as well, as I’m probably not the only user that don’t need all the available contact options. It’s a simple if condition when the contacts settings is looped. If it’s `‘’`_(empty)_ in the config the `<li>` won’t be returned, thus not showing the icon with a url without the username.

Hides the contact icon if empty in config

---

src/components/Sidebar/Contacts/__snapshots__/Contacts.test.js.snap
src/components/Sidebar/__snapshots__/Sidebar.test.js.snap
src/templates/__snapshots__/categories-list-template.test.js.snap
src/templates/__snapshots__/category-template.test.js.snap
src/templates/__snapshots__/index-template.test.js.snap
src/templates/__snapshots__/not-found-template.test.js.snap
src/templates/__snapshots__/page-template.test.js.snap
src/templates/__snapshots__/tag-template.test.js.snap
src/templates/__snapshots__/tags-list-template.test.js.snap
src/utils/get-contact-href.js
src/utils/get-contact-href.test.js

I noticed that the generated Telegram link was not up to date. The correct link should be _t.me/username_.
From the Telegram faq:
Source: https://telegram.org/faq#q-how-does-t-me-work

Fixed invalid Telegram contact url

---

content/pages/about.md
content/pages/contacts.md
content/posts/2016-01-09---Perfecting-the-Art-of-Perfection.md
content/posts/2016-01-12---The-Origins-of-Social-Stationery-Lettering.md
content/posts/2016-02-02---A-Brief-History-of-Typography.md
content/posts/2017-18-08---The-Birth-of-Movable-Type.md
content/posts/2017-19-08---Humane-Typography-in-the-Digital-Age.md
src/components/Layout/Layout.js
src/components/Layout/Layout.test.js
src/templates/page-template.js
src/templates/post-template.js
src/types/index.js

Currently Twitter cards don't contain a lot of information. This PR improves the look of these cards.
**Twitter card with current code**
**Twitter card with this PR**
You define the image used in the card by defining the socialImage tag in the md file for a page. If it hasn't been defined, we fall back to using your photo.jpg file. The twitter card description uses the existing description tag in the md file. 
I've also updated the sample md files with the socialImage tag.
Related to #350

Twitter cards

---

src/assets/scss/base/_generic.scss

Currently, the page content will jump slightly when you navigate between two pages if doing so causes the browser's scrollbar to appear/disappear. This simple fix prevents this from happening.
Introduced the following CSS to the html tag in the [_generic.scss](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/assets/scss/base/_generic.scss) file.
```css
margin-left: calc(100vw - 100%);
```
100vw is the size of the entire screen including the scrollbar. 100% is the entire screen **not** including the scrollbar. As a result, margin-left will be the same size as the size of the scrollbar on the right. If there is no scrollbar, then margin-left is 0.
Fixes #328

Prevent the page content from jumping due to scrollbar

---

content/posts/2016-01-09---Perfecting-the-Art-of-Perfection.md
content/posts/2016-01-12---The-Origins-of-Social-Stationery-Lettering.md
content/posts/2016-02-02---A-Brief-History-of-Typography.md
content/posts/2017-18-08---The-Birth-of-Movable-Type.md
content/posts/2017-19-08---Humane-Typography-in-the-Digital-Age.md
gatsby/on-create-node.js
static/admin/config.yml

This PR modifies the slug format in posts to represent a url friendly version of the title rather than a full url. This was modified both to reduce the redundant specification of `/posts/` in all post markdown file slugs, but also unlocks the ability to configure Netlify CMS `preview_path`, which this PR also adds.
See: https://www.netlifycms.org/docs/configuration-options/#preview_path
Fixes #500

Add netlify preview path support

---

postcss-config.js

On any browser, if the user configures their default font-size to be something larger than  `$typographic-base-font-size`, it causes the vertical alignment of the tags / home button to be off-center. This is because `height` and `line-height` wind up resolving to different values respectively.
Thus, this PR includes includes `height` in the `pxtorem()` config.
**Before:** 
**After:**
Hope this helps!

Include height in postcss pxtorem config

---

Dockerfile.production

Fix this error on docker build :
⚠ mozjpeg pre-build test failed
ℹ compiling from source
✖ Error: Command failed: /bin/sh -c autoreconf -fiv
Docker builds worked fine until I've got this error with mozjpeg. Adding libtool and automake to apt packages fixed the issue.

Fix mozjpeg unability to compile from source

---

static/admin/config.yml

The gatsby lumen starter currently supports a `socialImage` field in markdown content that will set the `twitter:image` and `og:image` meta tags in the layout component. This feature was added by [this merge](https://github.com/alxshelepenok/gatsby-starter-lumen/pull/375). This PR adds an "Social Image" widget that allows users to set the socialImage field through the netlifycms admin page.

Add social image widget to Netlify CMS config

---

gatsby-config.js

Because we use gatsby-plugin-offline and it caches every request have `static` in URL request like request to static/media so it show the images that not the same in folder static/media.

bugfix/ Edit gatsby plugin offline prevent cache static/media

---

README.md
package.json

Simplify documentation by only using `yarn`, instead of using both `npm` and `yarn`.

Replace npm with yarn commands

---

Dockerfile.production

When I tried to build an image using `Dockerfile.production` in my environment, it failed. This is a PR for the fix.
**Python**  
The package name seems to have changed.
```
ERROR: unable to select packages:
python (no such package):
required by: world[python]
ERROR: Service 'web' failed to build: The command '/bin/sh -c apk update && apk add --no-cache make git 
python autoconf g++ libc6-compat libjpeg-turbo-dev libpng-dev nasm libtool automake' returned a non-zero code: 1
```
**vips-dev**
```
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
<command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
<command-line>: note: this is the location of the previous definition
../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
24 | #include …
```

Fix Dockerfile.production

---

src/assets/scss/_variables.scss

This PR replace the `/` slash operator to `math.div` because the `/` operator for division get deprecated.
https://sass-lang.com/documentation/breaking-changes/slash-div
Also, deprecation warning messages about slash operator do not appear anymore in console.
fixes #955

Replace deprecated slash SASS operator to `math.div`

---

src/assets/scss/_variables.scss

I found the following warning right after `gatsby develop`.
⠋ Building development bundle
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($typographic-root-font-size, 100)
More info and automated migrator: https://sass-lang.com/d/slash-div
╷
28 │  $typographic-leading: round(16 * ($typographic-root-font-size / 100) * $typographic-base-line-height);
│                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
src/assets/scss/_variables.scss 28:35  @import
src/assets/scss/init.scss 3:9          root stylesheet
Not yet, but I believe this PR can fix it.

fix slash div warning
